apiVersion: v2
name: hh-ru-auto-resume-raising
description: A Helm chart for HH.ru auto resume raising bot
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - hh.ru
  - resume
  - automation
  - bot
home: https://github.com/staners2/hh-ru-auto-resume-raising
sources:
  - https://github.com/staners2/hh-ru-auto-resume-raising
maintainers:
  - name: staners2