# Default values for hh-ru-auto-resume-raising
image:
  repository: ghcr.io/staners2/hh-ru-auto-resume-raising
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

resources:
  limits:
    cpu: 50m
    memory: 32Mi
  requests:
    cpu: 5m
    memory: 16Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Persistent Volume configuration for storing schedules
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 100Mi
  storageClass: ""
  existingClaim: ""

# Environment variables for the bot
env:
  # Telegram bot configuration
  TELEGRAM_TOKEN: ""
  ADMIN_TG: ""
  
  # HeadHunter credentials
  HH_LOGIN: ""
  HH_PASSWORD: ""
  
  # Additional settings
  TZ: "Europe/Moscow"
  PROXY: "None"
  SCHEDULE_INTERVAL: "3600"
