name: Release Helm Chart

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Update Chart version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/^version:.*/version: $VERSION/" .helm/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"$VERSION\"/" .helm/Chart.yaml

      - name: Package Helm Chart
        run: |
          helm package .helm/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tgz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: .
          chart_dir: .helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"